{
    people : [
    { Id: 'r1', Name: 'Mike' },
    { Id: 'r2', Name: 'Linda' },
    { Id: 'r3', Name: 'Don' },
    { Id: 'r4', Name: 'Karen' },
    { Id: 'r5', Name: 'Doug' },
    { Id: 'r6', Name: 'Peter' },
    { Id: 'r11', Name: 'Fred' },
    
    { Id: 'r12', Name: 'Anders' },
    { Id: 'r13', Name: 'Pete' },
    { Id: 'r14', Name: 'Francis' },
    { Id: 'r15', Name: 'Simbad' },
    { Id: 'r16', Name: 'David' },
    { Id: 'r21', Name: 'Dave' },
    { Id: 'r22', Name: 'Lindsay' },
    { Id: 'r23', Name: 'Paul' },
    { Id: 'r24', Name: 'Donald' },
    { Id: 'r25', Name: 'Max' },
    { Id: 'r26', Name: 'Magnus' },
    { Id: 'r31', Name: 'Mark' },
    { Id: 'r32', Name: 'Axel' },
    { Id: 'r33', Name: 'Kathryn' },
    { Id: 'r34', Name: 'Li' },
    { Id: 'r35', Name: 'Wei' },
    { Id: 'r36', Name: 'Chen' },
    
    { Id: 'r42', Name: 'Senol' },
    { Id: 'r43', Name: 'Taufik' },
    { Id: 'r44', Name: 'Xing' },
    { Id: 'r45', Name: 'Deiping' },
    { Id: 'r46', Name: 'Larry' },
    { Id: 'r52', Name: 'Lars' },
    { Id: 'r53', Name: 'Anna' },
    { Id: 'r54', Name: 'Anka' },
    { Id: 'r55', Name: 'Anki' },
    { Id: 'r56', Name: 'Torsten' },
    { Id: 'r61', Name: 'Karin' },
    { Id: 'r62', Name: 'Goran' },
    { Id: 'r63', Name: 'Petter' },
    { Id: 'r66', Name: 'Tommy' },
    
    { Id: 'r72', Name: 'Wei' },
    { Id: 'r73', Name: 'Eggbert' },
    { Id: 'r74', Name: 'Johnny2' },
    { Id: 'r75', Name: 'Lara' },
    { Id: 'r76', Name: 'Conny' },
    { Id: 'r81', Name: 'Annie' },
    { Id: 'r82', Name: 'Oscar' },
    { Id: 'r83', Name: 'Ax' },
    { Id: 'r84', Name: 'Danne' },
    { Id: 'r85', Name: 'Svenn' },
    { Id: 'r86', Name: 'Dirklas' },
    { Id: 'r91', Name: 'Klas' }
]
}